services:
  db_master:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql
  
  db_replica:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica_data:/var/lib/postgresql
    depends_on:
      - db_master


volumes:
  postgres_master_data:
  postgres_replica_data: