spring.application.name=demo
server.port=8000
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# secret key must use base64 and 256 bytes
# you can use btoa in js and atleast write 44 character
jwt.secret=YXNkc2FkbnFpZG5xd2Rvd3FuZG93cWttZHFvd25kaXFqbmNzYWtjbmFsc2tkbnNhbGRuc2FkbmFzbGtkbg==
# access token 15 minutes
jwt.expiration.ms=900000