quarkus.http.port=8001
quarkus.http.host=0.0.0.0

quarkus.http.root-path=/api
quarkus.jackson.serialization-inclusion=non_null

quarkus.mongodb.connection-string=mongodb://mongodb:password@localhost:27017/microservices?authSource=admin
quarkus.mongodb.database=microservices

quarkus.test.continuous-testing=disabled
quarkus.live-reload.instrumentation=true