spring.application.name=backend
server.port=8000
server.address=0.0.0.0
server.servlet.context-path=/api

spring.thymeleaf.check-template-location=false

spring.flyway.enabled=false 

spring.datasource.write.url=jdbc:postgresql://localhost:5432/test
spring.datasource.write.username=postgres
spring.datasource.write.password=password
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.url=jdbc:postgresql://localhost:5433/test 
spring.datasource.read.username=postgres
spring.datasource.read.password=password
spring.datasource.read.driver-class-name=org.postgresql.Driver


# secret key must use base64 and 256 bytes
jwt.secret=YXNkc2FkbnFpZG5xd2Rvd3FuZG93cWttZHFvd25kaXFqbmNzYWtjbmFsc2tkbnNhbGRuc2FkbmFzbGtkbg
# access token 1 hour
jwt.expiration.ms=3600000

security.ratelimit.max-request=5
security.ratelimit.time-window-ms=60000

spring.jackson.default-property-inclusion=non_null

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

spring.profiles.active=dev