spring.application.name=backend
server.port=8000
server.servlet.context-path=/api

spring.boot.admin.client.url=http://localhost:9000
spring.boot.admin.client.instance.management-url=http://localhost:8000/api/actuator
spring.boot.admin.client.instance.service-base-url=http://localhost:8000
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics

management.info.env.enabled = true
info.app.name=${spring.application.name}
info.app.version=0.0.1-SNAPSHOT
info.app.environment=${spring.profiles.active}

spring.thymeleaf.check-template-location=false

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# secret key must use base64 and 256 bytes
jwt.secret=YXNkc2FkbnFpZG5xd2Rvd3FuZG93cWttZHFvd25kaXFqbmNzYWtjbmFsc2tkbnNhbGRuc2FkbmFzbGtkbg
# access token 1 hour
jwt.expiration.ms=3600000

security.ratelimit.max-request=5
security.ratelimit.time-window-ms=60000

spring.jackson.default-property-inclusion=non_null

spring.jpa.open-in-view=false

spring.profiles.active=dev